repo_id: "amanuelbyte/african_speech_dataset_arz"
hf_token: null           # set via: export HF_TOKEN=hf_xxx (recommended)
moz_api_key: null        # set via: export MOZ_API_KEY=... (or set here)

data_dir: "./processed_data"
num_proc: 2
push_max_shard_size: "500MB"

audio:
  sampling_rate: 16000
  min_duration: 0.5
  max_duration: 30.0
  filter_by_duration: true   # duration is computed from headers/bytes (no torchcodec)

text:
  min_chars: 2
  max_chars: 500
  lowercase: true

datasets:
  - name: ismaeeelxd_egyptian_arabic_lectures
    enabled: true
    source: hf
    language: arz
    hf_path: ismaeeelxd/Egyptian-Arabic-Lectures
    split: "train"
    audio_col: audio
    text_col: transcription

  - name: amine_khelif_arabic_multidialect
    enabled: true
    source: hf
    language: arz
    hf_path: amine-khelif/arabic-multidialect
    split: "train"
    audio_col: audio
    text_col: sentence

  - name: mohamedgomaa30_egyptian_speech_clean_mgb3
    enabled: true
    source: hf
    language: arz
    hf_path: MohamedGomaa30/Egyptian-Speech-Clean-MGB3
    split: "train"
    audio_col: separated_target_audio
    text_col: text

  - name: mohamedgomaa30_egy_speech_deepclean_v0
    enabled: true
    source: hf
    language: arz
    hf_path: MohamedGomaa30/Egy-Speech-DeepClean_v0
    split: "train"
    audio_col: separated_target_audio
    text_col: text
