repo_id: "amanuelbyte/african_speech_dataset_hau"
hf_token: null           # set via: export HF_TOKEN=hf_xxx (recommended)
moz_api_key: null        # set via: export MOZ_API_KEY=... (or set here)

data_dir: "./processed_data"
num_proc: 2
push_max_shard_size: "500MB"

audio:
  sampling_rate: 16000
  min_duration: 0.5
  max_duration: 30.0
  filter_by_duration: true   # duration is computed from headers/bytes (no torchcodec)

text:
  min_chars: 2
  max_chars: 500
  lowercase: true

datasets:
  - name: sib_fleurs_hau
    enabled: true
    source: hf
    language: hau
    hf_path: WueNLP/sib-fleurs
    subset: hau_Latn
    split: "train+validation"
    audio_col: audio
    text_col: transcription

  - name: nigerian_common_voice_hausa
    enabled: true
    source: hf
    language: hau
    hf_path: benjaminogbonna/nigerian_common_voice_dataset
    subset: hausa
    split: "train"
    audio_col: audio
    text_col: sentence

  - name: vaghawan_hausa_tts_22k
    enabled: true
    source: hf
    language: hau
    hf_path: vaghawan/hausa-tts-22k
    split: "train+validation+test"
    audio_col: audio
    text_col: text

  - name: suleiman2003_hausa_speech_processed2
    enabled: true
    source: hf
    language: hau
    hf_path: suleiman2003/hausa-speech-processed2
    split: "train"
    audio_col: audio
    text_col: transcript

  - name: shunyalabs_hausa_speech_dataset
    enabled: true
    source: hf
    language: hau
    hf_path: shunyalabs/hausa-speech-dataset
    split: "train+validation+test"
    audio_col: audio
    text_col: transcript

  - name: common_voice_mozilla_24_hau
    enabled: true
    source: mozilla_cv
    language: hau
    moz_dataset_id: "cmj8u3p6w00alnxxbby9yqbms"
    cv_folder: "ha"
    audio_col: audio
    text_col: text

  - name: bible_tts_hausa
    enabled: true
    source: hf
    language: hau
    hf_path: vpetukhov/bible_tts_hausa
    split: "train+dev+test"
    audio_col: audio
    text_col: sentence

  - name: aybee5_hausa_large_tts
    enabled: true
    source: hf
    language: hau
    hf_path: Aybee5/Hausa-large-tts
    split: "train"
    audio_col: audio
    text_col: text

  - name: zoelaenskii_zinny_hau_asr
    enabled: true
    source: hf
    language: hau
    hf_path: zoelaenskii/zinny
    subset: hau_asr
    split: "train+validation+test"
    audio_col: audio
    text_col: transcription

  - name: zoelaenskii_zinny_hau_tts
    enabled: true
    source: hf
    language: hau
    hf_path: zoelaenskii/zinny
    subset: hau_tts
    split: "train+validation+test"
    audio_col: audio
    text_col: text

